### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by peterbrinck** [shiroge/shiroge.github.io#15]
I've found this with 700+ free icons
Maybe they would match the theme of a dungeon crawler better than Bootstraps default Glyphicons?

http://opengameart.org/content/700-rpg-icons

EDIT:
Even better!!
http://game-icons.net/ - And they're SVG!

**Comment by shiroge** [comment]
I had already made my way into game-icons. Real nice. I've downloaded their full pack and will certainly use them.

Also added a credits line at the bottom of the page. I'll pull them all when it's ready.
