### ISSUE TITLE
The new battle system is broken

### ISSUE THREAD

**Issue by peterbrinck** [shiroge/shiroge.github.io#3]
The new battle system you've introduced doesn't work very well.

My fireball is level 13, and deal 12330 damage
So when ever a battle starts, in idle mode, the fireball is automatically fired, and kills every enemy instant, until the monsters gets a lot stronger!

The way it was before, it was still possible for the player to die, but now it's not

Does it make sense?

**Comment by shiroge** [comment]
What is your MGC stat? Fireball level 13 shouldn't deal that much damage unless you have MGC at the 90~100 range, and with those stats, you should be able to kill enemies instantly on the lower floors. Now that I changed the way monsters are handled, I can create new floors easily. Right now there are only 10, but for the next update I'm aiming for at least 100 floors.

That being said, I will probably reduce the impact MGC has on Fireball/Cure on the future though. I'm still trying to find a nice balance. Right now MGC seems to be leveling way too fast too. Balancing is hard!

**Comment by peterbrinck** [comment]
Ahaaa, I see!
Yeah, my MGC is 98

And yes, MGC is the fastest leveling stat

But then there's no problem with the combat system! :smile:
