### ISSUE TITLE
JS error when upgrading from v0.9 to v0.9.1

### ISSUE THREAD

**Issue by mattgiltaji** [shiroge/shiroge.github.io#44]
I think there is something incompatible with the v0.9 savegames when starting up 0.9.1.
I'm getting a javascript error:

upgrades.js:239 Uncaught TypeError: Cannot set property 'shown' of undefined
loadUpgradeList @ upgrades.js:239
self.load @ upgrades.js:223
loadAll @ system.js:45
startTheEngine @ system.js:147
main @ system.js:104

Do i need to do a hard reset?

**Comment by shiroge** [comment]
I think I know what the problem is. A hard reset would fix it, but it's not necessary (unless you want to play it right now). I'll try to fix it ASAP.

**Comment by shiroge** [comment]
I've pushed a temporary fix. It should solve the issue, but you might lose some upgrades.

**Comment by mattgiltaji** [comment]
@shiroge thanks it's working now. I had to re-buy upgrades, but the prices are much cheaper now so it's not really a problem.
