### ISSUE TITLE
Auto-Shooting ideas

### ISSUE THREAD

**Issue by peterbrinck** [shiroge/shiroge.github.io#9]
Some ideas for the Auto-Shooting upgrade
After the combat update, the Auto-Shooting only fires once a fight
<hr>
When first bought (level 1) the Auto-Shooting upgrade should fire once every XX second when in a fight.
Then when you get enough Excelia you can upgrade Auto-Shooting, so it shoots faster, and then keep leveling it up, so it shoots faster and faster.
And maybe an upgrade for the Auto-Shooting so that you can choose your own Damage giving spell, instead of just Fireball, but that's more an idea for the future when more spells are added

**Comment by shiroge** [comment]
It only auto-fired once before the update too. Another upgrade that changes it to every few turns might be a good idea though.

But then it would have to be changed from a preemptive strike to actually use a turn, or it would be too powerful.

On other note, thanks for your dedication to the game, I hope you're enjoying it. :)
